site_name: monoDrive Simulator
repo_url: https://github.com/monodriveio/client
docs_dir: docs
theme:
  name: 'ivory'
  navigation_depth: 1
  collapse_navigation: true

nav:
- monoDrive: index.md
- About monoDrive : intro_information.md
- Getting Started : [
  Getting_Started.md,
  monoDrive_home/getting_started/Windows.md,
  monoDrive_home/getting_started/Linux.md
]
- Products : 
  - Simulator : Simulator.md
  - Scenario Editor : [
      scenario_editor/scenario_intro.md,
      scenario_editor/scenarios.md,
      scenario_editor/scenario_files.md,
      scenario_editor/trajectory_files.md,
      scenario_editor/roads.md
    ]
  - Real-to-Virtual: [
    r2v/about.md,
    r2v/data_collection_quick_start.md,
    r2v/data_processing_quick_start.md,
    r2v/data_processing_output.md,
    r2v/r2v_maps.md
  ]

- Simulator API :
  - Introduction: monoDrive_home/API.md
  - Sensors: [
    monoDrive_home/Common.md,
    monoDrive_home/Camera.md,
    monoDrive_home/Collision.md,
    monoDrive_home/GPS.md,
    monoDrive_home/IMU.md,
    monoDrive_home/Lidar.md,
    monoDrive_home/OccupancyGrid.md,
    monoDrive_home/Radar.md,
    monoDrive_home/RPM.md,
    monoDrive_home/State-sensor.md,
    monoDrive_home/Ultrasonic.md,
    monoDrive_home/Viewport.md]
  - Simulator : monoDrive_home/Simulator-Configuration.md
  - Vehicle : [
    monoDrive_home/Vehicle-Configuration.md,
    monoDrive_home/Vehicle-PhysX.md]
  - Weather: monoDrive_home/Weather.md
  
- Tutorials:
  - Co-simulation Tutorials: [monoDrive_home/CarSim.md]
  - LabVIEW Tutorials: [LV_client/tutorials/Setup.md,
    LV_client/tutorials/AddSensors.md,
    LV_client/tutorials/Sensor_Palette.md,
    LV_client/tutorials/Lidar.md, 
    LV_client/tutorials/Simulator_configuration.md,
    LV_client/tutorials/Loading_Maps.md,
    LV_client/tutorials/Weather.md,
    LV_client/tutorials/Remote_Connection.md,
    LV_client/tutorials/wheel_integration.md 
    ]

- monoDrive Clients: 
  - Introduction: monodrive_clients.md
  - C++ Client:
    - C++ Quick Start: cpp_client/cpp_quick_start.md
    - ROS Quick Start: cpp_client/ros_quick_start.md
    - C++ Examples: cpp_client/cpp_examples.md
    - ROS Examples: cpp_client/ros_examples.md

  - LabVIEW Client: 
    - Quick Start: 
      - Setup: LV_client/quick_start/LabVIEW_client_quick_start.md
      - Run Examples: LV_client/quick_start/LabVIEW_run_examples.md
      - Configuration Examples: LV_client/quick_start/LabView_configurations.md
      - FAQ: LV_client/quick_start/FAQ.md
    - LabVIEW Detailed Help:
      - Examples:
          - mono1_pilot_example.vi: LV_client/examples/mono1_pilot_example.md
          - mono2_scenario_example.vi: LV_client/examples/mono2_scenario_example.md
          - mono3_replay_example.vi: LV_client/examples/mono3_replay_example.md
          - mono4_hil_example.vi: LV_client/examples/mono4_hil_example.md
          - mono5_radar_example.vi: LV_client/examples/mono5_radar_example.md
          - mono6_pilot_example_fixed_time.vi: LV_client/examples/mono6_pilot_example_fixed_time.md

      - Controls:
          - monoDrive.ctl: LV_client/structures/monoDrive.md
      - Sensors:
          - mono_camera.vi: LV_client/sensors/mono_camera.md
          - mono_depth_camera.vi: LV_client/sensors/mono_depth_camera.md
          - mono_semantic_camera.vi: LV_client/sensors/mono_semantic_camera.md
          - mono_camera_grayscale.vi: LV_client/sensors/mono_camera_grayscale.md
          - mono_occupancy_grid.vi: LV_client/sensors/mono_occupancy_grid.md
          - mono_gps.vi: LV_client/sensors/mono_gps.md
          - mono_imu.vi: LV_client/sensors/mono_imu.md
          - mono_lidar.vi: LV_client/sensors/mono_lidar.md
          - mono_semantic_lidar.vi: LV_client/sensors/mono_semantic_lidar.md
          - mono_radar.vi: LV_client/sensors/mono_radar.md
          - mono_rpm.vi: LV_client/sensors/mono_rpm.md
          - mono_state_sensor.vi: LV_client/sensors/mono_state_sensor.md
          - mono_ultrasonic.vi: LV_client/sensors/mono_ultrasonic.md
          - mono_collision.vi: LV_client/sensors/mono_collision.md
          - mono_viewport.vi: LV_client/sensors/mono_viewport.md
          - mono_fisheye_camera.vi: LV_client/sensors/mono_fisheye_camera.md

      - Weather:
          - mono_get_weather.vi: LV_client/weather/mono_get_weather.md
          - mono_weather_update.vi: LV_client/weather/mono_weather_update.md
          - mono_weather_id.vi: LV_client/weather/mono_weather_id.md
      - Tools:
          - mono_collision_plots.vi: LV_client/tools/mono_collision_plots.md
          - mono_create_replay.vi: LV_client/tools/mono_create_replay.md
          - mono_plot_radar_target_by_name.vi: LV_client/tools/mono_plot_radar_target_by_name.md
          - mono_radar_data_cube_plotter.vi: LV_client/tools/mono_radar_data_cube_plotter.md
          - mono_save_camera_images.vi: LV_client/tools/mono_save_camera_images.md
          - mono_start_fixed_time.vi: LV_client/tools/mono_start_fixed_time.md
          - mono_start_hil.vi: LV_client/tools/mono_start_hil.md
          - mono_start_lane_follower.vi: LV_client/tools/mono_start_lane_follower.md
          - mono_start_pilot.vi: LV_client/tools/mono_start_pilot.md
          - mono_start_replay.vi: LV_client/tools/mono_start_replay.md
          - mono_start_scenario.vi: LV_client/tools/mono_start_scenario.md
          - monoDrive.vi: LV_client/tools/monoDrive.md
          - mono_test_FPS_by_sensor.vi: LV_client/tools/mono_test_FPS_by_sensor.md

      - Simulator:
          - mono_set_running_mode.vi: LV_client/simulator/mono_set_running_mode.md
          - mono_connect.vi: LV_client/simulator/mono_connect.md
          - mono_header.vi: LV_client/simulator/mono_header.md
          - mono_send_command.vi: LV_client/simulator/mono_send_command.md
          - mono_send_step.vi: LV_client/simulator/mono_send_step.md
          - mono_init.vi: LV_client/simulator/mono_init.md
          - mono_check_simulator_version.vi: LV_client/simulator/mono_check_simulator_version.md
      - Utilities:
          - mono_build_json.vi: LV_client/utilities/mono_build_json.md
          - mono_build_version_msg.vi: LV_client/utilities/mono_build_version_msg.md
          - mono_calculate_average.vi: LV_client/utilities/mono_calculate_average.md
          - mono_calculate_orientation_xyz.vi: LV_client/utilities/mono_calculate_orientation_xyz.md
          - mono_check_path.vi: LV_client/utilities/mono_check_path.md
          - mono_check_simulator.vi: LV_client/utilities/mono_check_simulator.md
          - mono_convert_polar_to_rectangular.vi: LV_client/utilities/mono_convert_polar_to_rectangular.md
          - mono_draw_lanes_coord.vi: LV_client/utilities/mono_draw_lanes_coord.md
          - mono_draw_spawn_positions.vi: LV_client/utilities/mono_draw_spawn_positions.md
          - mono_Error_Fork_Stacker.vi: LV_client/utilities/mono_Error_Fork_Stacker.md
          - mono_filter_average_by_target.vi: LV_client/utilities/mono_filter_average_by_target.md
          - mono_generate_frame.vi: LV_client/utilities/mono_generate_frame.md
          - mono_get_map.vi: LV_client/utilities/mono_get_map.md
          - mono_get_number_frames.vi: LV_client/utilities/mono_get_number_frames.md
          - mono_get_number_points_lidar.vi: LV_client/utilities/mono_get_number_points_lidar.md
          - mono_get_spawn_position.vi: LV_client/utilities/mono_get_spawn_position.md
          - mono_get_start_points.vi: LV_client/utilities/mono_get_start_points.md
          - mono_get_stream_dimensions.vi: LV_client/utilities/mono_get_stream_dimensions.md
          - mono_intensity_to_color.vi: LV_client/utilities/mono_intensity_to_color.md
          - mono_lidar_packages.vi: LV_client/utilities/mono_lidar_packages.md
          - mono_lidar_plot.vi: LV_client/utilities/mono_lidar_plot.md
          - mono_parse_lidar_configuration.vi: LV_client/utilities/mono_parse_lidar_configuration.md
          - mono_obtain_timestamp.vi: LV_client/utilities/mono_obtain_timestamp.md
          - mono_parse_map_data.vi: LV_client/utilities/mono_parse_map_data.md
          - mono_parse_simulator_config.vi: LV_client/utilities/mono_parse_simulator_config.md
          - mono_parse_simulator_version.vi: LV_client/utilities/mono_parse_simulator_version.md
          - mono_parse_start_points.vi: LV_client/utilities/mono_parse_start_points.md
          - mono_proccess_annotation_data.vi: LV_client/utilities/mono_proccess_annotation_data.md
          - mono_read_file.vi: LV_client/utilities/mono_read_file.md
          - mono_read_trajectory.vi: LV_client/utilities/mono_read_trajectory_frame.md
          - mono_replace_ego_spawn_position.vi: LV_client/utilities/mono_replace_ego_spawn_position.md
          - mono_scale_map.vi: LV_client/utilities/mono_scale_map.md
          - mono_send_fixed_step_command.vi: LV_client/utilities/mono_send_fixed_step_command.md
          - mono_send_pilot_scenario.vi: LV_client/utilities/mono_send_pilot_scenario.md
          - mono_send_radar_cube_flag.vi: LV_client/utilities/mono_send_radar_cube_flag.md
          - mono_send_scenario_config.vi: LV_client/utilities/mono_send_scenario_config.md
          - mono_send_simulator_config.vi: LV_client/utilities/mono_send_simulator_config.md
          - mono_send_trajectory.vi: LV_client/utilities/mono_send_trajectory.md
          - mono_send_vehicle_command.vi: LV_client/utilities/mono_send_vehicle_command.md
          - mono_sensor_parser.vi: LV_client/utilities/mono_sensor_parser.md
          - mono_set_map.vi: LV_client/utilities/mono_set_map.md
          - mono_draw_map.vi: LV_client/utilities/mono_draw_map.md
          - mono_velodyne_parse.vi: LV_client/utilities/mono_velodyne_parse.md
          - mono_replace_ego_pose.vi: LV_client/utilities/mono_replace_ego_pose.md
          - mono_replace_ego_pose_legacy.vi: LV_client/utilities/mono_replace_ego_pose_legacy.md
          - mono_add_tcp_connection.vi: LV_client/utilities/mono_add_tcp_connection.md
          - mono_close_tcp_connections.vi: LV_client/utilities/mono_close_tcp_connections.md
          - mono_parse_depth_data.vi: LV_client/utilities/mono_parse_depth_data.md
          - mono_calculate_image_indexes.vi: LV_client/utilities/mono_calculate_image_indexes.md
          - mono_process_image_data.vi: LV_client/utilities/mono_process_image_data.md
          - mono_radar_sample.vi: LV_client/utilities/mono_radar_sample.md


      - Shared Libraries:
          - mono_control.vi: LV_client/shared_libraries/mono__control.md
          - mono_control_vehicle.vi: LV_client/shared_libraries/mono__control__vehiclec.md
          - mono_init.vi: LV_client/shared_libraries/mono__initc.md
          - mono_kf_update.vi: LV_client/shared_libraries/mono__kf__update.md
          - mono_kf_init.vi: LV_client/shared_libraries/mono_kf_init.md

  - Python Client:
    - Quick Start: python_client/quick_start.md
    - Examples: python_client/examples.md
        
extra_css:
    - css/extra.css        
        
markdown_extensions:
  - admonition
